# Agentic RAG API Configuration

# OpenAI Configuration
openai:
  api_key: ""  # Will be overridden by environment variable
  model: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 1000

# Model Configuration
model_config:
  response_model: "gpt-4o-mini"
  grader_model: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 1000

# Application Configuration
app:
  log_level: "INFO"

# Document Processing
document:
  chunk_size: 1000
  chunk_overlap: 200
  max_chunks: 100

# RAG Configuration
rag:
  top_k: 5
  similarity_threshold: 0.7
  max_context_length: 4000

# Prompts Configuration
prompts:
  GRADE_PROMPT: |
    You are a document relevance grader. Your task is to determine if the retrieved documents are relevant to the user's question.
    
    Question: {question}
    Retrieved Context: {context}
    
    Grade the relevance using a binary score:
    - "yes" if the documents are relevant and can help answer the question
    - "no" if the documents are not relevant or insufficient
    
    Consider:
    1. Does the context contain information directly related to the question?
    2. Is there enough detail to provide a meaningful answer?
    3. Are the documents from reliable sources?
    
    Binary Score:
  REWRITE_PROMPT: |
    You are a question rewriter. The user's question was not answered well by the retrieved documents.
    
    Original Question: {question}
    
    Please rewrite the question to be more specific, clear, or focused. Consider:
    1. Breaking down complex questions into simpler parts
    2. Adding context or clarification
    3. Making the question more searchable
    4. Using different terminology that might match the available documents
    
    Rewritten Question:
  
  GENERATE_PROMPT: |
    You are an AI assistant that answers questions based on retrieved document content.
    
    Question: {question}
    Retrieved Context: {context}
    
    Please provide a comprehensive answer based on the context provided. If the context doesn't contain enough information to answer the question completely, acknowledge what you can answer and what information is missing.
    
    Answer:





